#################
# Site settings #
#################
encoding: utf-8
lang: en-US
title: "teguha.sh"
description: >
  A description for your page.

# URL including protocol for your site (use "http://localhost:4000" if developing locally)
# url: "https://teguhash.github.io"
url: "http://localhost:4000"
# Subpath if necessary
baseurl: ""

markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true

theme: kiko-minus

# Custom user stylesheet
# css:
#   src: "/assets/css/user-style.css"

# List of links to show in the navbar with display name and URL
nav:
  - name: "#TIL"
    url: "/til"
  - name: "About"
    url: "/about"
  - name: "Archive"
    url: "/archive"

fathom:
  enabled: false
  script_src: "https://analytics.example.tld/tracker.js"
  site_id: "SITEID"

# Copyright details for footer
copyright:
  year: 2020
  name: "teguha.sh"


############
# Excludes #
############
exclude:
  - README.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - kiko-minus.gemspec
  - .gitignore
  - .gitlab-ci.yml
  - .jekyll-cache
  - .image-optim-cache
  - "*.gem"
  - assets/img_archive


###########
# Plugins #
###########
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-zopfli
  - jekyll-image-optim
  - jekyll-paginate-v2
  - jekyll-analytics


################
# Gem settings #
################
# jekyll-pagination-v2
pagination:
  enabled: true
  per_page: 7
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# jekyll-seo-tag
twitter:
  username: "teguhash"
author: "Teguh A.S. Hidayat"
social:
  name: "Teguh A.S. Hidayat"
  links:
    - https://twitter.com/teguhash
    - https://www.linkedin.com/in/teguhash
    - https://github.com/teguhash

# jekyll-image-optim
image_optim:
  archive_dir: "assets/img_archive"
  cache_file: ".image-optim-cache"
  image_glob: "assets/img/**/*.{gif,png,jpg,jpeg}"


###################
# Jekyll settings #
###################
sass:
  style: compressed
permalink: pretty


# GA settings
jekyll_analytics:
  GoogleAnalytics:
    id: UA-159912088-1
    anonymizeIp: false 

# Disqus
disqus:
  shortname: teguhash-github

timezone: Asia/Jakarta
