#################
# Site settings #
#################
encoding: utf-8
lang: en-US
title: "Your title"
description: >
  A description for your page.

# URL including protocol for your site (use "http://localhost:4000" if developing locally)
url: "https://teguhash.github.io"
#url: "localhost:4000"
# Subpath if necessary
baseurl: ""

markdown: kramdown
kramdown:
  math_engine: mathjax

theme: kiko-minus

# Custom user stylesheet
# css:
#   src: "/assets/css/user-style.css"

# List of links to show in the navbar with display name and URL
nav:
  - name: "About"
    url: "/about"
  - name: "Archive"
    url: "/archive"
  - name: "Wikipedia Articles"
    url: "/wikipedia"

# Refer to https://posativ.org/isso/docs/configuration/client for config options
isso:
  enabled: false
  prefix: ""
  script_src: ""
  css: "true"
  lang: "en"
  reply_to_self: false
  require_author: "false"
  require_email: "false"
  max_comments_top: "10"
  max_comments_nested: "5"
  reveal_on_click: "10"
  avatar: "false"
  # avatar_bg: "#f0f0f0"
  # avatar_fg: "#9abf88 #5698c4 #e279a3 #9163b6"
  vote: "true"
  vote_levels: ""
  feed: "false"

fathom:
  enabled: false
  script_src: "https://analytics.example.tld/tracker.js"
  site_id: "SITEID"

# Copyright details for footer
copyright:
  year: 2020
  name: "teguha.sh"


############
# Excludes #
############
exclude:
  - README.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - kiko-minus.gemspec
  - .gitignore
  - .gitlab-ci.yml
  - .jekyll-cache
  - .image-optim-cache
  - "*.gem"
  - assets/img_archive


###########
# Plugins #
###########
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-zopfli
  - jekyll-image-optim


################
# Gem settings #
################
# jekyll-pagination-v2
pagination:
  enabled: true
  per_page: 7
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# jekyll-seo-tag
twitter:
  username: "teguhash"
author: "Teguh A.S. Hidayat"
social:
  name: "Teguh A.S. Hidayat"
  links:
    - https://twitter.com/teguhash
    - https://www.linkedin.com/in/teguhash
    - https://github.com/teguhash

# jekyll-image-optim
image_optim:
  archive_dir: "assets/img_archive"
  cache_file: ".image-optim-cache"
  image_glob: "assets/img/**/*.{gif,png,jpg,jpeg}"


###################
# Jekyll settings #
###################
sass:
  style: compressed
permalink: pretty

timezone: Asia/Jakarta
